name: Docker Setup
description: Sets up a Docker builder with inline caching and multiplatorm building capabilities

inputs:
  docker-hub-user:
    description: User for authentication against Docker Hub
    required: true
  docker-hub-pass:
    description: Docker Hub password of the given user
    required: true
  image:
    description: Docker image name
    required: true
  context:
    description: Docker build context
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-pass }}
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=registry,ref=${{ inputs.image }}
        cache-to: type=inline
        context: ${{ inputs.context }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.image }}
