on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tier1:
    name: Build Tier 1 images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - ["alpine", "1maa/alpine:3.15"]
          - ["alpine", "1maa/alpine:latest"]
          - ["bitcoin", "1maa/bitcoind:22.0"]
          - ["mysql", "1maa/mysql:8.0"]
          - ["sqlite", "1maa/sqlite:latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-setup
        with:
          context: ${{ matrix.images[0] }}
          docker-hub-pass: ${{ secrets.DOCKER_HUB_PASS }}
          docker-hub-user: 1maa
          image: ${{ matrix.images[1] }}

  tier2:
    name: Build Tier 2 images
    runs-on: ubuntu-latest
    needs: [tier1]
    strategy:
      fail-fast: false
      matrix:
        images:
          - ["sakila", "1maa/sakila:latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-setup
        with:
          context: ${{ matrix.images[0] }}
          docker-hub-pass: ${{ secrets.DOCKER_HUB_PASS }}
          docker-hub-user: 1maa
          image: ${{ matrix.images[1] }}
