on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tier1:
    name: Build Tier 1 images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - ["alpine", "1maa/alpine:3.15"]
          - ["alpine", "1maa/alpine:latest"]
          - ["mysql", "1maa/mysql:8.0"]
          - ["sqlite", "1maa/sqlite:latest"]
    env:
      CONTEXT: ${{ matrix.images[0] }}
      IMAGE: ${{ matrix.images[1] }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.IMAGE }}
          cache-to: type=inline
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ env.IMAGE }}

  tier2:
    name: Build Tier 2 images
    runs-on: ubuntu-latest
    needs: [tier1]
    strategy:
      fail-fast: false
      matrix:
        images:
          - ["sakila", "1maa/sakila:latest"]
    env:
      CONTEXT: ${{ matrix.images[0] }}
      IMAGE: ${{ matrix.images[1] }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.IMAGE }}
          cache-to: type=inline
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ env.IMAGE }}
